In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
# Check for the null values 
dataset.isna().apply(pd.value_counts)

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
False      10000       10000    10000        10000      10000   10000  10000   

       Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
False   10000    10000          10000      10000           10000   

       EstimatedSalary  Exited  
False            10000   10000

In [6]:
#check the correlation of the data
dataset.corr()

RowNumber  CustomerId  CreditScore       Age    Tenure  \
RowNumber         1.000000    0.004202     0.005840  0.000783 -0.006495   
CustomerId        0.004202    1.000000     0.005308  0.009497 -0.014883   
CreditScore       0.005840    0.005308     1.000000 -0.003965  0.000842   
Age               0.000783    0.009497    -0.003965  1.000000 -0.009997   
Tenure           -0.006495   -0.014883     0.000842 -0.009997  1.000000   
Balance          -0.009067   -0.012419     0.006268  0.028308 -0.012254   
NumOfProducts     0.007246    0.016972     0.012238 -0.030680  0.013444   
HasCrCard         0.000599   -0.014025    -0.005458 -0.011721  0.022583   
IsActiveMember    0.012044    0.001665     0.025651  0.085472 -0.028362   
EstimatedSalary  -0.005988    0.015271    -0.001384 -0.007201  0.007784   
Exited           -0.016571   -0.006248    -0.027094  0.285323 -0.014001   

                  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber       -0.009067       0.007246   0.000599        0.012044   
CustomerId      -0.012419       0.016972  -0.014025        0.001665   
CreditScore      0.006268       0.012238  -0.005458        0.025651   
Age              0.028308      -0.030680  -0.011721        0.085472   
Tenure          -0.012254       0.013444   0.022583       -0.028362   
Balance          1.000000      -0.304180  -0.014858       -0.010084   
NumOfProducts   -0.304180       1.000000   0.003183        0.009612   
HasCrCard       -0.014858       0.003183   1.000000       -0.011866   
IsActiveMember  -0.010084       0.009612  -0.011866        1.000000   
EstimatedSalary  0.012797       0.014204  -0.009933       -0.011421   
Exited           0.118533      -0.047820  -0.007138       -0.156128   

                 EstimatedSalary    Exited  
RowNumber              -0.005988 -0.016571  
CustomerId              0.015271 -0.006248  
CreditScore            -0.001384 -0.027094  
Age                    -0.007201  0.285323  
Tenure                  0.007784 -0.014001  
Balance                 0.012797  0.118533  
NumOfProducts           0.014204 -0.047820  
HasCrCard              -0.009933 -0.007138  
IsActiveMember         -0.011421 -0.156128  
EstimatedSalary         1.000000  0.012097  
Exited                  0.012097  1.000000

In [8]:
df_encoded=pd.get_dummies(dataset, columns=['Geography','Gender'])
df_encoded.head()

RowNumber  CustomerId   Surname  CreditScore  Age  Tenure    Balance  \
0          1    15634602  Hargrave          619   42       2       0.00   
1          2    15647311      Hill          608   41       1   83807.86   
2          3    15619304      Onio          502   42       8  159660.80   
3          4    15701354      Boni          699   39       1       0.00   
4          5    15737888  Mitchell          850   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0              1          1               1        101348.88       1   
1              1          0               1        112542.58       0   
2              3          1               0        113931.57       1   
3              2          0               0         93826.63       0   
4              1          1               1         79084.10       0   

   Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                 1                  0                0              1   
1                 0                  0                1              1   
2                 1                  0                0              1   
3                 1                  0                0              1   
4                 0                  0                1              1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [12]:
X=df_encoded[['CreditScore','Age','Tenure','Balance','NumOfProducts','HasCrCard','IsActiveMember','EstimatedSalary','Geography_France','Geography_Germany','Geography_Spain','Gender_Female','Gender_Male']].values

In [13]:
y=df_encoded[['Exited']]

In [14]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# 1- Sigmoid function

In [26]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 300)

Epoch 1/300
250/250 [==============================] - 1s 1ms/step - loss: 0.5924 - accuracy: 0.7944
Epoch 2/300
250/250 [==============================] - 0s 2ms/step - loss: 0.4407 - accuracy: 0.7960
Epoch 3/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4316 - accuracy: 0.7960
Epoch 4/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4275 - accuracy: 0.7960
Epoch 5/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4243 - accuracy: 0.7960
Epoch 6/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4217 - accuracy: 0.7960
Epoch 7/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4192 - accuracy: 0.7960
Epoch 8/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4178 - accuracy: 0.8220
Epoch 9/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4167 - accuracy: 0.8257
Epoch 10/300
250/250 [==============================] - 0s 1ms/step - loss: 0.4156 - accura

In [29]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1549,   46],
       [ 271,  134]], dtype=int64)

In [30]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  84.15 %


# 2- Softplus function

In [34]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softplus'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6960 - accuracy: 0.5181
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4358 - accuracy: 0.7962
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4269 - accuracy: 0.8067
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4239 - accuracy: 0.8154
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8184
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4182 - accuracy: 0.8216
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4159 - accuracy: 0.8256
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4139 - accuracy: 0.8280
Epoch 9/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8298
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4100 - accura

In [35]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1557,   38],
       [ 274,  131]], dtype=int64)

In [36]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  84.39999999999999 %


# 3- Softsign function

In [37]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softsign'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.7567 - accuracy: 0.7960
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4563 - accuracy: 0.7958
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4300 - accuracy: 0.7979
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4212 - accuracy: 0.8000
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4125 - accuracy: 0.8002
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4040 - accuracy: 0.8026
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3963 - accuracy: 0.8079
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3908 - accuracy: 0.8100
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3865 - accuracy: 0.8185
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3836 - accura

In [38]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 982us/step


array([[1514,   81],
       [ 202,  203]], dtype=int64)

In [39]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  85.85000000000001 %


# 4-Softmax Function

In [40]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'softmax'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 2ms/step - loss: 0.5925 - accuracy: 0.2040
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4415 - accuracy: 0.2040
Epoch 3/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4224 - accuracy: 0.2040
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4130 - accuracy: 0.2040
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4060 - accuracy: 0.2040
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4008 - accuracy: 0.2040
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3962 - accuracy: 0.2040
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3928 - accuracy: 0.2040
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3895 - accuracy: 0.2040
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3860 - accura

In [41]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[   0, 1595],
       [   0,  405]], dtype=int64)

In [42]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  20.25 %


# 5- Tanh Function

In [43]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'tanh'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6622 - accuracy: 0.7960
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4357 - accuracy: 0.8004
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8083
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4102 - accuracy: 0.8096
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3977 - accuracy: 0.8154
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3872 - accuracy: 0.8229
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3795 - accuracy: 0.8292
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3737 - accuracy: 0.8356
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3708 - accuracy: 0.8395
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3683 - accura

In [44]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1518,   77],
       [ 199,  206]], dtype=int64)

In [45]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.2 %


# 6- Swish Function

In [46]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'swish'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.7546 - accuracy: 0.7961
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4332 - accuracy: 0.8106
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4292 - accuracy: 0.8096
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4237 - accuracy: 0.8098
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4193 - accuracy: 0.8121
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4072 - accuracy: 0.8145
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3981 - accuracy: 0.8188
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3908 - accuracy: 0.8255
Epoch 9/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3849 - accuracy: 0.8319
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3808 - accura

In [47]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1518,   77],
       [ 192,  213]], dtype=int64)

In [48]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.55000000000001 %


# 7- Exponential Function

In [49]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'exponential'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 3.0640 - accuracy: 0.2040
Epoch 2/200
250/250 [==============================] - 0s 2ms/step - loss: 1.2584 - accuracy: 0.2042
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.6592 - accuracy: 0.6008
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.5045 - accuracy: 0.7916
Epoch 5/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4620 - accuracy: 0.7960
Epoch 6/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4466 - accuracy: 0.8009
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4390 - accuracy: 0.8015
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4343 - accuracy: 0.8081
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4307 - accuracy: 0.8099
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4278 - accura

In [50]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1532,   63],
       [ 204,  201]], dtype=int64)

In [51]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.65 %


# 8- Elu function

In [52]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'elu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6275 - accuracy: 0.7960
Epoch 2/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4343 - accuracy: 0.8070
Epoch 3/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4218 - accuracy: 0.8077
Epoch 4/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4119 - accuracy: 0.8120
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4026 - accuracy: 0.8145
Epoch 6/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3956 - accuracy: 0.8215
Epoch 7/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8271
Epoch 8/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3845 - accuracy: 0.8304
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3801 - accuracy: 0.8329
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3788 - accura

In [53]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1528,   67],
       [ 218,  187]], dtype=int64)

In [54]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  85.75 %


# 9- Selu function

In [55]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 13))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'selu'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size = 32, epochs = 200)

Epoch 1/200
250/250 [==============================] - 1s 1ms/step - loss: 0.6674 - accuracy: 0.7960
Epoch 2/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4339 - accuracy: 0.8040
Epoch 3/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4204 - accuracy: 0.8085
Epoch 4/200
250/250 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 0.8111
Epoch 5/200
250/250 [==============================] - 0s 1ms/step - loss: 0.4028 - accuracy: 0.8152
Epoch 6/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3940 - accuracy: 0.8205
Epoch 7/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3876 - accuracy: 0.8281
Epoch 8/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3840 - accuracy: 0.8332
Epoch 9/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3817 - accuracy: 0.8365
Epoch 10/200
250/250 [==============================] - 0s 1ms/step - loss: 0.3780 - accura

In [56]:
#Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5) #greater than 0.50 on scale 0 to 1
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
cm

63/63 [==============================] - 0s 1ms/step


array([[1538,   57],
       [ 222,  183]], dtype=int64)

In [57]:
acc=accuracy_score(Y_test, y_pred)
print('accurcy of  model: ',acc *100,'%')

accurcy of  model:  86.05000000000001 %
